### ISSUE TITLE
Post-processor doesnt roll up the multiple files appropriately

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy-plugins#151]
Ran the example and ended up with an empty status:

```
name: e2e-0
status: unknown
meta:
  type: summary
items:
- name: sonobuoy_results.yaml
  status: ""
  meta:
    file: results/global/sonobuoy_results.yaml
    type: file
  items:
  - name: junit_01.xml
    status: passed
    meta:
      file: /tmp/sonobuoy/results/junit_01.xml
      type: file
    items:
    - name: Kubernetes e2e suite
      status: passed
```

The status should have been rolled up. If not here, then in the sonobuoy core when grabbing them.
